# Generated by Django 5.2.1 on 2025-05-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hint',
            name='hint_number',
            field=models.IntegerField(default=1),
        ),
    ]
