# Generated by Django 5.2.1 on 2025-05-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hint_hint_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hint',
            name='title',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
