# Generated by Django 5.2.1 on 2025-05-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hint_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='score',
            field=models.IntegerField(default=500),
        ),
    ]
