# Generated by Django 5.2.1 on 2025-05-20 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customuser_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('hint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'hint')},
            },
        ),
    ]
