# Generated by Django 5.2.1 on 2025-05-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_challenge_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
